app = "api-rskcpw"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 2000
    hard_limit = 5000

[[vm]]
  cpu_kind = "performance"
  cpus = 10
  memory = "20gb"

[env]
  PYTHONOPTIMIZE = "1"
  UVLOOP_ENABLED = "1"
  TITAN_SECRET_KEY = "Titan_2026_Ultra_Fast"
  # توجيه الأوامر للأنوية الـ 10 والرام الـ 20
  UVICORN_WORKERS = "10"
  MAX_THREADS = "128"
  OMP_NUM_THREADS = "10"
